name: CI

on: [push]

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build App
        run: yarn build

      - name: Archive Production Build
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test-and-build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Download Build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Configure Deploy to Firebase in /github/workflows/main.yml, line 47
        run: echo Firebase Deploy
      # Add FIREBASE_TOKEN as a secret to your github project
      # Uncomment the following step to deploy to firebase
      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
